### ISSUE TITLE
Ghost in a Searchbar

### ISSUE THREAD

**Issue by drew0036** [drew0036/more-than-just-datum#1]
Hey @muxlowc,

I'm having a lot of trouble with the search bar icon in this assignment. It either squishes up or floats away. What can I do to get the icon and the bar in the right place?

![Screen Shot 2020-04-07 at 10 27 56 PM](https://user-images.githubusercontent.com/55107709/78738193-3ea26a80-791f-11ea-9cda-9611411e0ba2.png)

Thank you!

**Comment by muxlowc** [comment]
@drew0036 

1) hmm try changing your class from absolute to relative on your form, 
2)  also your unit surrounding your form should have these unit fractions: "unit xs-1 s-1 m-2-3 l-3-4"
3) change your pin-lb to pin-lc (you want it centred)/ it should be i-18 (so a bit small that what you have right now)

Hopefully that works?

**Comment by drew0036** [comment]
That helped, thank you!
