### ISSUE TITLE
Markbot Is Seeing Phantoms

### ISSUE THREAD

**Issue by drew0036** [drew0036/more-than-just-datum#2]
Hey @muxlowc,

I'm still having trouble with this one. I can't find the open tag that Markbot is talking about. 
![Screen Shot 2020-04-16 at 12 42 24 PM](https://user-images.githubusercontent.com/55107709/79483244-061a2500-7fe0-11ea-952f-fc76c9d01a01.png)
Any suggestions?

Thank you!

**Comment by muxlowc** [comment]
@drew0036 ah, yes so `<body>` doesnt=`<main>`, it just means that all of the content for your site needs to be inside of your `<body>`, so the reason it's mad is because you have your `<header>` outside of the body. hope that helps!

**Comment by drew0036** [comment]
Thank you!
