### ISSUE TITLE
So close!

### ISSUE THREAD

**Issue by drew0036** [drew0036/more-than-just-datum#3]
![Screen Shot 2020-04-16 at 6 24 23 PM](https://user-images.githubusercontent.com/55107709/79512535-a2a7eb80-800f-11ea-9265-e44b30863a6f.png)

Hey @muxlowc!

Almost got it, I just don't understand how to get the 400 size to have the p tags on the same line in the Nearby Playgrounds section. Please advise.

Thank you!

**Comment by drew0036** [comment]
Is it like a max height? Or a grid within the grid?

**Comment by muxlowc** [comment]
@drew0036 so theyre actually a list inside of a list, rather than just simply divs. Here's some code to get you started:

```
<div class="grid grid-stretch">
    <div class="panel-near unit [ xs-1 s-1 m-1-3 l-1-4 ] island-1-2">
      <h2 class="giga push-1-2">Nearest playgrounds</h2>

      <ul class="near-list list-group push-0">
        <li class="card island-1-2 push-1-2">
          <h3 class="mega push-0">373</h3>
          <dl class="list-group-inline push-0">
            <dt class="push-0 italic milli">Distance</dt>
            <dd class="push-0">0.75 km</dd>
          </dl>
        </li>
```

Hope that helps!

**Comment by drew0036** [comment]
It worked! Thank you! 😄
